// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badge: typeof import('./components/Badge.vue')['default']
    'Carbon:calendarSettings': typeof import('~icons/carbon/calendar-settings')['default']
    'Carbon:caretDown': typeof import('~icons/carbon/caret-down')['default']
    'Carbon:caretRight': typeof import('~icons/carbon/caret-right')['default']
    'Carbon:circleFilled': typeof import('~icons/carbon/circle-filled')['default']
    'Carbon:compare': typeof import('~icons/carbon/compare')['default']
    'Carbon:fileStorage': typeof import('~icons/carbon/file-storage')['default']
    'Carbon:listBoxes': typeof import('~icons/carbon/list-boxes')['default']
    'Carbon:network4': typeof import('~icons/carbon/network4')['default']
    'Carbon:textWrap': typeof import('~icons/carbon/text-wrap')['default']
    'Carbon:timer': typeof import('~icons/carbon/timer')['default']
    CarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CodeViewer: typeof import('./components/CodeViewer.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    DiffViewer: typeof import('./components/DiffViewer.vue')['default']
    Graph: typeof import('./components/Graph.vue')['default']
    ModuleId: typeof import('./components/ModuleId.vue')['default']
    ModuleList: typeof import('./components/ModuleList.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    OutputList: typeof import('./components/OutputList.vue')['default']
    PluginName: typeof import('./components/PluginName.vue')['default']
    RawConfig: typeof import('./components/RawConfig.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
    TreeBrowser: typeof import('./components/TreeBrowser.vue')['default']
  }
}

export {}
